language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://conventicgmbh.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "PpDafER3O5xq4GucsI4HEmT15bN8zUo3Yo1MLpzlxpmmyhG+ohptYRxMuKSN4U3nD2uLws3pNBJ/2WKBtcRvpNYagMmgdIY5c0SoM/c24BnSVdadkAFqo5dzlf7o7/ajwk/BKlvGIpVCo/VjarK+6kqdLeOSM74p5qczK3VUP7Bikcnu+5822mD4+dtYSKpAYsJQeIfYCyarOIaMDLLBaGClxpH2LWloSQVbVR3cwWFmbXc9MX3tDdqSBz05NU4/ShDL0g0qUHls+mXoR1Jr5DLAyMkVJ90Az+x76R3gBZy23H15w+hEQ58VhDeEq2rYu2DOCyV2sPwEwMPCZ+u/zpIn9LtMEgE+JCI/fYNl2SkagI8a0/zva2SLcF5roKokPnJq/V37W7zsp/YumGDGpgDuMfYfbvls3jZg86NFHYzA6jfWuocMDdr2AENdCXrbV3o6xuMfS4Thhv8lakLKOWbFBvWbgztZruQ8EMGWeCqMmLXaAAC58dUnHLq2igecWmuWtNX2hM8jQo3i5bpwrqJnoJyIUV8n9aQQdugV6DwXVy+RsHTYFbUOH5e9EVBfZDZaY+sNjt1W4rVimKZ3NBTd9FLbJq1BzQ5F+6u3omdYFeWueeB2H0I9lW6u3hEg5ooDFreWGPwQyG+9P0K67Wicd2GMA0R/80GpwPxuy50="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
