language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://conventicgmbh.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "FvUvc4sfCADsApuc0l/Mco6+sTFwUlJabZ4QqhSbqhgQP5dnE8SsS4MbY/P3MO2qUQNPtyzbOxJDH+uR4335KuhsSP/+ekDYru8v1R4wPLffHdb6ERv6uwmiXRC1/Y7r6fusVYatwT73wky8gk8XcmunYEmY6pXnlvOtG4jVqKbAbAYHz9/KIx2nYjxYhjqVIEfwa1LUhIHyoTrA+0vU+tcpjs3iARAw2JmmR+W4Pwzc22t42UqE2VZosnoKF5JSdCIctiFvdCofV2ujilWypOhWMB+gSTdh9Yc/AhT+GZrAqXSr343MVc5xCuhQmakcCgXnShpKmnlF/iRedNzEr7XMCHTkeFaHn+0leNjQ1xnSbtBk/PvCeN++w3US2eA0boBzG/qXxsjFozNlcSet/YeAf6EcFnC5mna7nCVekvmnu3hAK0wbf9bZ3v1NJk6yElhIGP63paGLkQ2JeETv4LBb8GRgHtEogI7HbxAdneLI2BQPCyjMcSVOtJMEuv3n4CxL1+/uOg7eDFCuKvTMCcwAkBvDrPFZ7ZIIZ/bdLiORGv+laB3T3E8lr8lrU7uhzG2RIVm/SnIA5Ol9Ij724xvAfC5gMeU+m/ODDiGmamwXabF0kqTXFwRoxJrfCENN40DGbI6hUoxfEquNJ3nK1FixTzEiaY7Ip+qVJlk6bEY="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
